import Script from "next/script";

/* ✅ Metadata */
export const metadata = {
  title: "Construz || Responsive Next Template",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", type: "image/png", sizes: "32x32", url: "/favicon.png" },
    ],
    apple: [
      { rel: "apple-touch-icon", sizes: "180x180", url: "/favicon.png" },
    ],
    shortcut: [{ rel: "shortcut icon", url: "/favicon.png" }],
  },
};

/* ✅ Global styles */
import "~/public/main-assets/css/fonts.css";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Tailwind CDN — Next.js safe */}
        <Script
          src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"
          strategy="beforeInteractive"
        />
      </head>
      <body className="antialiased bg-white text-gray-900">
        {children}
      </body>
    </html>
  );
}
